// <auto-generated />
namespace NivesBrelihPhotography.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27152015_AddedDisplayNameToUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27152015_AddedDisplayNameToUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201512271230592_27.15.2015_AddedDisplayNameToUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
