// <auto-generated />
namespace NivesBrelihPhotography.Migrations.NbpContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedPhotoAlbumnewPhotoProps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedPhotoAlbumnewPhotoProps));
        
        string IMigrationMetadata.Id
        {
            get { return "201606101444549_Added PhotoAlbum, new Photo Props"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
