// <auto-generated />
namespace NivesBrelihPhotography.Migrations.NbpContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedshowalbumoptiononblogmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedshowalbumoptiononblogmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201607081816303_Added show album option on blog model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
